# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
  LIBRARY = libeetrans.a
  
  OBJ = eet_calc.o eet_input.o eet_det.o eet_2e.o eet_dgefa.o  \
 eet_movecs_read.o eet_vectors_inp.o eet_fock.o \
 eet_dens_prod.o eet_omega2_mult.o eet_cis_read.o eet_print.o \
 eet_gen_den.o eet_coc.o eet_tran_dip.o eet_int_2e4c.o eet_int_2e4c_ex.o
 
  USES_BLAS = eet_dgefa.F
 


include ../config/makefile.h
include ../config/makelib.h

