# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
  LIBRARY = libebridge.a
  
  OBJ = ebt_calc.o ebt_input.o ebt_det.o ebt_2e.o ebt_dgefa.o       \
 ebt_movecs_read.o ebt_movecs_write.o ebt_vectors_inp.o ebt_fock.o  \
 ebt_dens_prod.o ebt_omega2_mult.o ebt_trans.o ebt_flib.o ebt_coc.o \
 ebt_2e2.o ebt_omega2_mult2.o ebt_dens_prod2.o full_Jab.o           \
 ebt_filename.o ebt_outfile.o ebt_tran_dip.o ebt_molecules_inp.o    \
 ebt_dip_coupling.o ebt_tran_dip2.o ebt_draw_xyz.o
 
  USES_BLAS = ebt_dgefa.F
 


include ../config/makefile.h
include ../config/makelib.h

