# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
  LIBRARY = libmonomer.a
  
  OBJ = mon_calc.o mon_input.o mon_det.o mon_2e.o mon_dgefa.o  \
 mon_movecs_read.o mon_vectors_inp.o mon_fock.o \
 mon_dens_prod.o mon_omega2_mult.o mon_cis_read.o mon_print.o \
 mon_gen_den.o mon_coc.o mon_tran_dip.o mon_int_2e4c.o mon_int_2e4c_ex.o
 
  USES_BLAS = mon_dgefa.F
 


include ../config/makefile.h
include ../config/makelib.h

